version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: timekeeper-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timekeeper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - timekeeper-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: timekeeper-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - timekeeper-network

volumes:
  postgres_data:

networks:
  timekeeper-network:
    driver: bridge